accounts/urls.py
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("post/", views.CreatePostView.as_view(),name='post'),
]

creators/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.HomePage.as_view(), name="home"),
    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import User

# Create your models here.
 
class User(auth.models.User, auth.models.PermissionsMixin):
    
 def __str__(self):
   return "@{}".format(self.username)

class Image(models.Model):
    image = models.ImageField(upload_to='images')

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Image


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

class MyForm(forms.Form):
   user_image=forms.ImageField()

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms
from .models import Image
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"


class CreatePostView(CreateView):
   template_name="accounts/post.html"
   model=Image
   fields="__all__"
   success_url=reverse_lazy("login")


    

creators/views.py
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = "index.html"

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block css_files %}

<link rel="stylesheet" href="{% static "accounts/login.css" %}" />

{% endblock %}



{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/post.html
{% load static %}
<html>
<head>
<title></title>



<link rel="stylesheet" href="{% static "accounts/post.css" %}" />


</head>
<body>
<div class="container">
    <h1>Welcome, {{ user.username }}</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button>Upload</button>
    </form>
</div>
</body>
</html>

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load static %}
{% load bootstrap3 %}



{% block css_files %}

<link rel="stylesheet" href="{% static "accounts/signup.css" %}" />

{% endblock %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Creators Lab</title>
  
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'creators/css/master.css'%}">
    {% block css_files %}{% endblock %}

  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
        <div class="container">

    <a class="navbar-brand mynav" href="{% url 'home' %}">Creators Lab</a>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
              <li><a href="{% url 'accounts:post' %}" class="btn btn-simple">Post</a></li>
              <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
                    {% else %}
    
                          <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
                          <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
                    {% endif %}
                </ul>



        </div>
    </nav>




        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block css_files %}

<link rel="stylesheet" href="{% static "index.css" %}" />

{% endblock %}

{% block content %}

<h1>Welcome to Creators Lab!</h1>

{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>

</div>




{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}